# Generated by Django 3.0.6 on 2020-05-26 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msrp', models.FloatField()),
                ('delivery', models.FloatField()),
                ('taxes', models.FloatField()),
                ('discount', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('is_pending', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('rate', models.FloatField()),
                ('discount', models.FloatField()),
                ('residual', models.FloatField()),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.Payment')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.PaymentType'),
        ),
        migrations.AddField(
            model_name='payment',
            name='trim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.Trim'),
        ),
    ]
